moveit_simple_controller_manager:
  controller_names:
    - fake_arm_controller
    - fake_gripper_controller

  fake_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

  fake_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - jaw1
      - jaw2

# Initial joint positions
initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  jaw1: 0.0
  jaw2: 0.0
