joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  joint2:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  joint3:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  joint4:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  joint5:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  joint6:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: false
    min_position: 0.0
    max_position: 0.0
  jaw1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: 0.0
    max_position: 0.015
  jaw2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: 0.0
    max_position: 0.015
