arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

# Note: gripper group removed since it's not a proper kinematic chain
# The gripper joints (jaw1, jaw2) will be controlled separately
